### ISSUE TITLE
Does not clear but draw above previous displayed keystrokes

### ISSUE THREAD

**Issue by axwnet** [ammgws/wshowkeys#3]
does not happen when window is switched in sway.
Void 5.13.19_1 x86_64-musl

**Comment by axwnet** [comment]
also flickers occasionally when mouse hovers above...

**Comment by rpigott** [comment]
Whoever maintains the aur package now points to this fork.

Anyway, this was a sway issue, resolved with swaywm/sway#6415.

**Comment by axwnet** [comment]
will try again once void has sway 1.7
